#ifndef PROTOCOL_H
#define PROTOCOL_H
typedef unsigned uint;

enum ENUM_MSG_TYPE{
    ENUM_MSG_TYPE_MIN=0,
    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_REGIST_RESPOND,
    ENUM_MSG_TYPE_LOGINT_RESPOND,
    ENUM_MSG_TYPE_FINDUSER_REQUEST,
    ENUM_MSG_TYPE_FINDUSERT_RESPOND,
    ENUM_MSG_TYPE_ONLINEUSER_REQUEST,
    ENUM_MSG_TYPE_ONLINEUSER_RESPOND,
    ENUM_MSG_TYPE_ADDFRIEND_REQUEST,
    ENUM_MSG_TYPE_ADDFRIEND_RESPOND,
    ENUM_MSG_TYPE_ADDFRIEND_AGREE_REQUEST,
    ENUM_MSG_TYPE_ADDFRIEND_AGREE_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DEL_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DEL_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_FRIEND_REQUEST,
    ENUM_MSG_TYPE_CHAT_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DIKER_FILE_REQUEST,
    ENUM_MSG_TYPE_DIKER_FILE_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DEL_FILE_REQUEST,
    ENUM_MSG_TYPE_DEL_FILE_RESPOND,
    ENUM_MSG_TYPE_RENAME_FILE_REQUEST,
    ENUM_MSG_TYPE_RENAME_FILE_RESPOND,
    ENUM_MSG_TYPE_MAX=99999,
};


struct PDU{
    uint uiTotalLen;
    uint uiMsgLen;
    uint uiType;
    char caData[64];
    char caMsg[];

};
struct FileInfo{
    char caName[32];
    uint uiType;
};
PDU*mkPDU(uint uiMsgLen=0);




#endif // PROTOCOL_H
